// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGM0taPQ3mm2wvFEVXZ4mZ8DsLEG-EK1o',
    appId: '1:107702478603:web:b3a8b8863f43c380a5640e',
    messagingSenderId: '107702478603',
    projectId: 'pawsome-app-7abf4',
    authDomain: 'pawsome-app-7abf4.firebaseapp.com',
    storageBucket: 'pawsome-app-7abf4.firebasestorage.app',
    measurementId: 'G-ZEQ8QDX6W3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBA-GVxGPZ9tkkPQEeDSn-aQgelaVgQf_g',
    appId: '1:107702478603:android:49cebe172869812ca5640e',
    messagingSenderId: '107702478603',
    projectId: 'pawsome-app-7abf4',
    storageBucket: 'pawsome-app-7abf4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyoeeVXTGGV2sNhbgE8SV53LrqZzO-Asc',
    appId: '1:107702478603:ios:9ec784f5563e6d76a5640e',
    messagingSenderId: '107702478603',
    projectId: 'pawsome-app-7abf4',
    storageBucket: 'pawsome-app-7abf4.firebasestorage.app',
    iosBundleId: 'com.example.pawsome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyoeeVXTGGV2sNhbgE8SV53LrqZzO-Asc',
    appId: '1:107702478603:ios:9ec784f5563e6d76a5640e',
    messagingSenderId: '107702478603',
    projectId: 'pawsome-app-7abf4',
    storageBucket: 'pawsome-app-7abf4.firebasestorage.app',
    iosBundleId: 'com.example.pawsome',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGM0taPQ3mm2wvFEVXZ4mZ8DsLEG-EK1o',
    appId: '1:107702478603:web:5640826a06444fb3a5640e',
    messagingSenderId: '107702478603',
    projectId: 'pawsome-app-7abf4',
    authDomain: 'pawsome-app-7abf4.firebaseapp.com',
    storageBucket: 'pawsome-app-7abf4.firebasestorage.app',
    measurementId: 'G-EZXF9MC3MN',
  );

}