// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUZbM6yW8bL8pjD10JMmefksT_5d088Ng',
    appId: '1:615853406315:web:5a424aac50409a76ee192e',
    messagingSenderId: '615853406315',
    projectId: 'pawsome-2235c',
    authDomain: 'pawsome-2235c.firebaseapp.com',
    storageBucket: 'pawsome-2235c.firebasestorage.app',
    measurementId: 'G-45FX1HD29W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeCy5eJRTr4qzfs6lUYIML1qDa4JgUAl0',
    appId: '1:615853406315:android:67beaa49f4112296ee192e',
    messagingSenderId: '615853406315',
    projectId: 'pawsome-2235c',
    storageBucket: 'pawsome-2235c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrN-8Neg42Y6-H4oStomuvOgvDprn3DsM',
    appId: '1:615853406315:ios:b6bdcbafae0a5f81ee192e',
    messagingSenderId: '615853406315',
    projectId: 'pawsome-2235c',
    storageBucket: 'pawsome-2235c.firebasestorage.app',
    iosBundleId: 'com.example.pawsome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrN-8Neg42Y6-H4oStomuvOgvDprn3DsM',
    appId: '1:615853406315:ios:b6bdcbafae0a5f81ee192e',
    messagingSenderId: '615853406315',
    projectId: 'pawsome-2235c',
    storageBucket: 'pawsome-2235c.firebasestorage.app',
    iosBundleId: 'com.example.pawsome',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUZbM6yW8bL8pjD10JMmefksT_5d088Ng',
    appId: '1:615853406315:web:32a361f91d39b932ee192e',
    messagingSenderId: '615853406315',
    projectId: 'pawsome-2235c',
    authDomain: 'pawsome-2235c.firebaseapp.com',
    storageBucket: 'pawsome-2235c.firebasestorage.app',
    measurementId: 'G-GNG3KGXVHV',
  );
}
